2025-04-20 10:31:10.365006: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-04-20 10:31:10.485344: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2025-04-20 10:31:10.485373: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2025-04-20 10:31:10.515090: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-04-20 10:31:16.246730: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2025-04-20 10:31:16.247081: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2025-04-20 10:31:16.247104: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/aver/.local/share/uv/python/cpython-3.10.17-linux-x86_64-gnu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aver/.local/share/uv/python/cpython-3.10.17-linux-x86_64-gnu/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aver/Machine_Learning/AML_MiniProject/src/data_preprocessing.py", line 248, in <module>
    main()
  File "/home/aver/Machine_Learning/AML_MiniProject/src/data_preprocessing.py", line 235, in main
    preprocess_data(
  File "/home/aver/Machine_Learning/AML_MiniProject/src/data_preprocessing.py", line 172, in preprocess_data
    splits = download_data(
  File "/home/aver/Machine_Learning/AML_MiniProject/src/data_preprocessing.py", line 102, in download_data
    test_ds = load_dataset("liamdugan/raid_test", "raid_test", split="test")
  File "/home/aver/Machine_Learning/AML_MiniProject/.venv/lib/python3.10/site-packages/datasets/load.py", line 2062, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/aver/Machine_Learning/AML_MiniProject/.venv/lib/python3.10/site-packages/datasets/load.py", line 1782, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/aver/Machine_Learning/AML_MiniProject/.venv/lib/python3.10/site-packages/datasets/load.py", line 1652, in dataset_module_factory
    raise e1 from None
  File "/home/aver/Machine_Learning/AML_MiniProject/.venv/lib/python3.10/site-packages/datasets/load.py", line 1578, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'liamdugan/raid_test' doesn't exist on the Hub or cannot be accessed.
